# 개발용
services:
  app:
    container_name: festamate
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: gobongbab/festamate:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - USE_PROFILE=dev
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=
       # Spring Boot에서 Firebase 키 파일 위치를 읽는 환경 변수
      - GOOGLE_FIREBASE_KEY=/config/festamate-firebase-key.json
      - TZ=Asia/Seoul
    volumes: # EC2 호스트 경로와 Docker 컨테이너 내부의 특정 경로를 연결(마운트)하는 역할
      # EC2의 키 파일 경로: /home/ubuntu/festamate-firebase-key.json 컨테이너 내부 경로:/config/festamate-firebase-key.json
      - /home/ubuntu/festamate-firebase-key.json:/config/festamate-firebase-key.json:ro # 읽기 전용(ro)으로 마운트 권장
    networks:
      - festamate-network
    depends_on:
      - redis

  # Redis 캐시 서버 설정
  redis:
    image: redis:6.2.4-alpine
    container_name: redis-dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data # Redis 데이터 영속성을 위한 볼륨
    networks:
      - festamate-network

volumes:
  redis-dev-data: # Redis 데이터 저장용 볼륨

networks:
  festamate-network: # 서비스 간 통신을 위한 브릿지 네트워크
    driver: bridge
