# 개발용
FROM openjdk:17-jdk-slim

WORKDIR /app

COPY build/libs/Festamate-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

# 개발 프로필 활성화
ENV USE_PROFILE=dev
ENTRYPOINT ["java", "-Dspring.profiles.active=${USE_PROFILE}", "-jar", "app.jar"]