spring:
  config:
    activate:
      on-profile: local
    # .env import
    import: optional:file:.env[.properties]
  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  sql:
    init:
      mode: never
