spring:
  config:
    # /home/ubuntu/ 경로에 있는 .env 파일을 선택적으로 임포트
    import: "optional:file:/home/ubuntu/.env[.properties]"
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
          defer-datasource-initialization: true
        default_batch_fetch_size: 1000
  data:
    redis:
      host: localhost #docker-compose.yml에서 Redis 서비스의 이름을 사용
      port: 6379 # Docker에서 Redis 컨테이너가 6379 포트를 사용하므로, 호스트에서도 동일한 포트를 사용
      password:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: profile
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: id
  cloud:
    aws:
      credentials:
        access-key: ${AWS_SNS_ACCESS_KEY}
        secret-key: ${AWS_SNS_SECRET_KEY}
      region:
        static: ap-northeast-1 # 도쿄 리전 (SNS 관련)
jwt:
  secret: ${JWT_SECRET}
naver:
  ocr:
    api:
      url: ${OCR_API_URL}
      secret: ${OCR_API_SECRET}
sentry:
  dsn: ${SENTRY_DSN}
  send-default-pii: true
  max-request-body-size: small
server:
  forward-headers-strategy: framework
  servlet:
    encoding: # 인코딩
      enabled: true
      charset: UTF-8
      force: true
kakao: # 설정값들을 직접 참조 하기 위함
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  token-uri: ${KAKAO_TOKEN_URI}
  user-info-uri: ${KAKAO_USER_INFO_URI}

# AWS S3 관련 설정
cloud:
  aws:
    s3: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${IAM_USER_ACCESS_KEY}
      secret-key: ${IAM_USER_SECRET_KEY}
    region:
      static: ap-northeast-2 # 서울 리전 (S3 관련)
    stack:
      auto: false
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus # prometheus 엔드포인트 포함
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true # Prometheus 엔드포인트 활성화
admin:
  loginId: ${ADMIN_LOGIN_ID}
  password: ${ADMIN_PASSWORD}
  kakaoId: ${ADMIN_KAKAO_ID}
logging:
  level:
    com.gobongbob.festamate: DEBUG
