name: Build and Deploy to EC2

on:
  # develop 브랜치에 push가 발생했을 때 실행
  push:
    branches:
      - develop
  # develop 브랜치로 PR이 생성됐을 때 실행
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: gobongbab/festamate:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 환경 변수 파일 생성 (민감한 정보는 GitHub Secrets에서 가져옴)
            cat > .env << EOF
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASS=${{ secrets.DB_PASS }}
            EOF
            
            # 이전 컨테이너 중지 및 제거
            docker-compose down
            
            # 최신 이미지 pull
            docker-compose pull
            
            # 컨테이너 시작
            docker-compose up -d
            
            # 사용하지 않는 이미지 정리 (선택사항)
            docker image prune -af
